# Statistical Analysis

In [1]:
from pandas import (
    read_excel,
    DataFrame, 
    ExcelWriter,
    to_numeric,
    Series,
)
from pathlib import Path
import numpy as np
import scipy.stats as stats
from IPython.core.interactiveshell import InteractiveShell
from openpyxl.styles import Border, Side


# Enable automatic display of all expressions in the cell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# config
project_root = Path.cwd()
project_root

PosixPath('/home/alexandrod/Desktop/analyse_uni\uf022bi_variee')

In [3]:
df_path = project_root / "analysededonnees.xlsx"
df_path

PosixPath('/home/alexandrod/Desktop/analyse_uni\uf022bi_variee/analysededonnees.xlsx')

In [4]:
df = read_excel(df_path)

df.columns

Index(['Q0-Acceptez-vous de participer à cette enquête?', 'Date du jour:',
       'Q1-Quel est votre Nom?', 'Q2-Veuillez indiquer votre Age.',
       'Q3-Quel est votre sexe?', 'Q4-Choisi la commune.',
       'Q4a-Choisi la section communale.', 'Q4b-Choisi la localité.',
       'Q4-Choisi le niveau d'education.',
       'Q5-Combien de personnes vivent-ils sous le même toit?',
       'Q6-Quel type de culture pratiquez-vous?', 'Autres, Précisez.',
       'Q7-Appartenez-vous à une coopérative agricole?',
       'Q8-Avez-vous déjà contracté un crédit agricol?',
       'Q9-Si oui, combien de fois avez-vous obtenu un crédit agricole ces 3 dernières années?',
       'Q10-Montant total du dernier crédit contracté',
       'Q11-Temps écoulé entre la demande et l'approbation du crédit.',
       'Q12-Avez-vous rencontré des difficultés pour accéder aux crédits?',
       'Si oui, lesquelles?',
       'Q13- Avez-vous investi au moins 80 % du prêt reçu dans l'agriculture?',
       'Si non, où avez-vous investi le reste?', 'Si autre, précisez.',
       'Q14- Quels types d'investissements agricoles avez-vous réalisés avec le crédit ?',
       'Autre,Precisez',
       'Q15- Avez-vous constaté une augmentation de vos revenus agricoles depuis l'obtention du crédit?',
       'Si oui, de combien environ ?',
       'Q16- Avez-vous généré des revenus complémentaires en dehors de votre production agricole principal?',
       'Q17- Votre condition de logement s'est-elle améliorée après l'obtention du crédit?',
       'Q18- Votre sécurité alimentaire s'est-elle améliorée grâce au crédit?',
       'Q19-Avez-vous remboursé intégralement votre dernier crédit agricole?',
       'Si non, quelles étaient les principales raisons ?',
       'Precisez, si autre.',
       'Q20-Quel pourcentage de votre crédit avez-vous déjà remboursé ?',
       'Q21-Quel est votre niveau actuel d'endettement en pourcentage par rapport à vos revenus annuels ?',
       'Q22- Avez-vous des comités mis en place pour la gestion des crédits et des risques financiers ?',
       'Q23- Avez-vous pu vendre vos produits agricoles à des acheteurs externes grâce aux informations sur les prix ?',
       'Q24- Combien de transactions commerciales avez-vous effectuées avec des acheteurs externes au cours des 12 derniers mois ?',
       'meta/instanceID', '_id', '_uuid', '_submission_time', '_index',
       '_parent_table_name', '_parent_index', '_tags', '_notes', '_version',
       '_duration', '_submitted_by', '_xform_id'],
      dtype='object')

## First Treatment

---

[x] remove non participant <br/>
[x] fill NAN

In [5]:
df['Q0-Acceptez-vous de participer à cette enquête?'].value_counts()

Q0-Acceptez-vous de participer à cette enquête?
Oui, j'accepte de participer          37
Non, je ne souhaite pas participer     4
Name: count, dtype: int64

In [6]:
remove_non_participant = df[df["Q0-Acceptez-vous de participer à cette enquête?"]!="Non, je ne souhaite pas participer"]
remove_non_participant

,Q0-Acceptez-vous de participer à cette enquête?,Date du jour:,Q1-Quel est votre Nom?,Q2-Veuillez indiquer votre Age.,Q3-Quel est votre sexe?,Q4-Choisi la commune.,Q4a-Choisi la section communale.,Q4b-Choisi la localité.,Q4-Choisi le niveau d'education.,Q5-Combien de personnes vivent-ils sous le même toit?,...,_submission_time,_index,_parent_table_name,_parent_index,_tags,_notes,_version,_duration,_submitted_by,_xform_id
1,"Oui, j'accepte de participer",2025-02-02,Renette,35.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,7.0,...,2025-02-20 19:24:41,2,NaN,-1,NaN,NaN,202502201908,NaN,thalie,839246
2,"Oui, j'accepte de participer",2025-02-02,Rachel,45.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-20 19:41:05,3,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
3,"Oui, j'accepte de participer",2025-02-02,Julien,48.0,Homme,Thomassique,Matelgate,Dalegran,Aucune scolarisation,5.0,...,2025-02-20 19:57:39,4,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
5,"Oui, j'accepte de participer",2025-02-02,Gaston,57.0,Homme,Thomassique,Matelgate,Bouloum,Aucune scolarisation,6.0,...,2025-02-20 20:02:38,6,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
6,"Oui, j'accepte de participer",2025-02-03,Gilbert,56.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,6.0,...,2025-02-20 20:04:02,7,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
7,"Oui, j'accepte de participer",2025-02-03,Alberta,52.0,Femme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,6.0,...,2025-02-20 20:06:52,8,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
8,"Oui, j'accepte de participer",2025-02-03,Iliobert,64.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,4.0,...,2025-02-20 20:11:24,9,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
9,"Oui, j'accepte de participer",2025-02-03,Denise,27.0,Femme,Thomassique,Lociane,Bokbanik,Primaire,3.0,...,2025-02-20 20:12:47,10,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
10,"Oui, j'accepte de participer",2025-02-03,Reginald,48.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,3.0,...,2025-02-20 20:28:00,11,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
11,"Oui, j'accepte de participer",2025-02-03,Melouna,46.0,Femme,Thomassique,Lociane,Bokbanik,Primaire,5.0,...,2025-02-20 20:41:10,12,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
12,"Oui, j'accepte de participer",2025-02-03,Dieiumene,54.0,Femme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,7.0,...,2025-02-20 20:53:55,13,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
13,"Oui, j'accepte de participer",NaT,Mesadieu,55.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,6.0,...,2025-02-20 20:57:10,14,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
14,"Oui, j'accepte de participer",2025-02-03,Dieumetre,62.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,7.0,...,2025-02-20 21:00:10,15,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
15,"Oui, j'accepte de participer",2025-02-03,Dieula,47.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,8.0,...,2025-02-20 21:47:15,16,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
16,"Oui, j'accepte de participer",2025-02-03,Meyouse,35.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,4.0,...,2025-02-20 21:48:52,17,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
18,"Oui, j'accepte de participer",2025-02-03,Richemond,55.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,7.0,...,2025-02-20 21:50:12,19,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
19,"Oui, j'accepte de participer",2025-02-03,Fenelon,49.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,8.0,...,2025-02-20 21:54:44,20,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
20,"Oui, j'accepte de participer",2025-02-03,Desire,58.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,5.0,...,2025-02-20 21:58:21,21,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
21,"Oui, j'accepte de participer",2025-02-03,Wedline,36.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,6.0,...,2025-02-21 00:08:11,22,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
22,"Oui, j'accepte de participer",2025-02-03,Yvener,65.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,7.0,...,2025-02-21 00:12:04,23,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
23,"Oui, j'accepte de participer",2025-02-03,Noé,73.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,5.0,...,2025-02-21 00:15:03,24,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
24,"Oui, j'accepte de participer",2025-02-03,Thomas,49.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,7.0,...,2025-02-21 00:18:05,25,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
25,"Oui, j'accepte de participer",2025-02-03,Ulrick,73.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,6.0,...,2025-02-21 00:21:20,26,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
26,"Oui, j'accepte de participer",2025-02-03,Herold,47.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,8.0,...,2025-02-21 00:23:57,27,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
27,"Oui, j'accepte de participer",2025-02-05,Wilfrid,57.0,Homme,Thomassique,Matelgate,Dalegran,Aucune scolarisation,7.0,...,2025-02-21 00:26:04,28,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
28,"Oui, j'accepte de participer",2025-02-05,Edouard,67.0,Homme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 00:35:35,29,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
29,"Oui, j'accepte de participer",2025-02-05,Edline,48.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 00:40:35,30,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
30,"Oui, j'accepte de participer",2025-02-05,Adelina,43.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,3.0,...,2025-02-21 00:51:06,31,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
32,"Oui, j'accepte de participer",2025-02-05,Bernard,45.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,7.0,...,2025-02-21 00:59:14,33,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
33,"Oui, j'accepte de participer",2025-02-05,Gerald,63.0,Homme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 01:01:41,34,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
34,"Oui, j'accepte de participer",2025-02-05,Adlin,47.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,4.0,...,2025-02-21 01:05:07,35,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
35,"Oui, j'accepte de participer",2025-02-05,Madeleine,39.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,7.0,...,2025-02-21 01:07:27,36,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
36,"Oui, j'accepte de participer",2025-02-05,Mariane,28.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,3.0,...,2025-02-21 01:08:46,37,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
37,"Oui, j'accepte de participer",2025-02-05,Ronald,56.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,6.0,...,2025-02-21 01:09:46,38,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
38,"Oui, j'accepte de participer",2025-02-05,Jean René,54.0,Homme,Thomassique,Matelgate,Dalegran,Universitaire,8.0,...,2025-02-21 01:12:35,39,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
39,"Oui, j'accepte de participer",2025-02-05,Diogène,45.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,4.0,...,2025-02-21 01:14:15,40,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246
40,"Oui, j'accepte de participer",2025-02-05,Mathilde,37.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,2.0,...,2025-02-21 01:16:55,41,NaN,-1,NaN,NaN,202502201923,NaN,thalie,839246

In [7]:
remove_np_fillna = remove_non_participant.fillna("n/a")
remove_np_fillna

,Q0-Acceptez-vous de participer à cette enquête?,Date du jour:,Q1-Quel est votre Nom?,Q2-Veuillez indiquer votre Age.,Q3-Quel est votre sexe?,Q4-Choisi la commune.,Q4a-Choisi la section communale.,Q4b-Choisi la localité.,Q4-Choisi le niveau d'education.,Q5-Combien de personnes vivent-ils sous le même toit?,...,_submission_time,_index,_parent_table_name,_parent_index,_tags,_notes,_version,_duration,_submitted_by,_xform_id
1,"Oui, j'accepte de participer",2025-02-02 00:00:00,Renette,35.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,7.0,...,2025-02-20 19:24:41,2,n/a,-1,n/a,n/a,202502201908,n/a,thalie,839246
2,"Oui, j'accepte de participer",2025-02-02 00:00:00,Rachel,45.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-20 19:41:05,3,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
3,"Oui, j'accepte de participer",2025-02-02 00:00:00,Julien,48.0,Homme,Thomassique,Matelgate,Dalegran,Aucune scolarisation,5.0,...,2025-02-20 19:57:39,4,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
5,"Oui, j'accepte de participer",2025-02-02 00:00:00,Gaston,57.0,Homme,Thomassique,Matelgate,Bouloum,Aucune scolarisation,6.0,...,2025-02-20 20:02:38,6,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
6,"Oui, j'accepte de participer",2025-02-03 00:00:00,Gilbert,56.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,6.0,...,2025-02-20 20:04:02,7,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
7,"Oui, j'accepte de participer",2025-02-03 00:00:00,Alberta,52.0,Femme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,6.0,...,2025-02-20 20:06:52,8,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
8,"Oui, j'accepte de participer",2025-02-03 00:00:00,Iliobert,64.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,4.0,...,2025-02-20 20:11:24,9,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
9,"Oui, j'accepte de participer",2025-02-03 00:00:00,Denise,27.0,Femme,Thomassique,Lociane,Bokbanik,Primaire,3.0,...,2025-02-20 20:12:47,10,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
10,"Oui, j'accepte de participer",2025-02-03 00:00:00,Reginald,48.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,3.0,...,2025-02-20 20:28:00,11,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
11,"Oui, j'accepte de participer",2025-02-03 00:00:00,Melouna,46.0,Femme,Thomassique,Lociane,Bokbanik,Primaire,5.0,...,2025-02-20 20:41:10,12,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
12,"Oui, j'accepte de participer",2025-02-03 00:00:00,Dieiumene,54.0,Femme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,7.0,...,2025-02-20 20:53:55,13,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
13,"Oui, j'accepte de participer",n/a,Mesadieu,55.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,6.0,...,2025-02-20 20:57:10,14,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
14,"Oui, j'accepte de participer",2025-02-03 00:00:00,Dieumetre,62.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,7.0,...,2025-02-20 21:00:10,15,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
15,"Oui, j'accepte de participer",2025-02-03 00:00:00,Dieula,47.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,8.0,...,2025-02-20 21:47:15,16,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
16,"Oui, j'accepte de participer",2025-02-03 00:00:00,Meyouse,35.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,4.0,...,2025-02-20 21:48:52,17,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
18,"Oui, j'accepte de participer",2025-02-03 00:00:00,Richemond,55.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,7.0,...,2025-02-20 21:50:12,19,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
19,"Oui, j'accepte de participer",2025-02-03 00:00:00,Fenelon,49.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,8.0,...,2025-02-20 21:54:44,20,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
20,"Oui, j'accepte de participer",2025-02-03 00:00:00,Desire,58.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,5.0,...,2025-02-20 21:58:21,21,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
21,"Oui, j'accepte de participer",2025-02-03 00:00:00,Wedline,36.0,Femme,Thomassique,Lociane,Bokbanik,Secondaire,6.0,...,2025-02-21 00:08:11,22,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
22,"Oui, j'accepte de participer",2025-02-03 00:00:00,Yvener,65.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,7.0,...,2025-02-21 00:12:04,23,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
23,"Oui, j'accepte de participer",2025-02-03 00:00:00,Noé,73.0,Homme,Thomassique,Lociane,Bokbanik,Aucune scolarisation,5.0,...,2025-02-21 00:15:03,24,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
24,"Oui, j'accepte de participer",2025-02-03 00:00:00,Thomas,49.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,7.0,...,2025-02-21 00:18:05,25,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
25,"Oui, j'accepte de participer",2025-02-03 00:00:00,Ulrick,73.0,Homme,Thomassique,Lociane,Bokbanik,Primaire,6.0,...,2025-02-21 00:21:20,26,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
26,"Oui, j'accepte de participer",2025-02-03 00:00:00,Herold,47.0,Homme,Thomassique,Lociane,Bokbanik,Secondaire,8.0,...,2025-02-21 00:23:57,27,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
27,"Oui, j'accepte de participer",2025-02-05 00:00:00,Wilfrid,57.0,Homme,Thomassique,Matelgate,Dalegran,Aucune scolarisation,7.0,...,2025-02-21 00:26:04,28,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
28,"Oui, j'accepte de participer",2025-02-05 00:00:00,Edouard,67.0,Homme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 00:35:35,29,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
29,"Oui, j'accepte de participer",2025-02-05 00:00:00,Edline,48.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 00:40:35,30,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
30,"Oui, j'accepte de participer",2025-02-05 00:00:00,Adelina,43.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,3.0,...,2025-02-21 00:51:06,31,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
32,"Oui, j'accepte de participer",2025-02-05 00:00:00,Bernard,45.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,7.0,...,2025-02-21 00:59:14,33,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
33,"Oui, j'accepte de participer",2025-02-05 00:00:00,Gerald,63.0,Homme,Thomassique,Matelgate,Dalegran,Primaire,5.0,...,2025-02-21 01:01:41,34,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
34,"Oui, j'accepte de participer",2025-02-05 00:00:00,Adlin,47.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,4.0,...,2025-02-21 01:05:07,35,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
35,"Oui, j'accepte de participer",2025-02-05 00:00:00,Madeleine,39.0,Femme,Thomassique,Matelgate,Dalegran,Primaire,7.0,...,2025-02-21 01:07:27,36,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
36,"Oui, j'accepte de participer",2025-02-05 00:00:00,Mariane,28.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,3.0,...,2025-02-21 01:08:46,37,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
37,"Oui, j'accepte de participer",2025-02-05 00:00:00,Ronald,56.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,6.0,...,2025-02-21 01:09:46,38,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
38,"Oui, j'accepte de participer",2025-02-05 00:00:00,Jean René,54.0,Homme,Thomassique,Matelgate,Dalegran,Universitaire,8.0,...,2025-02-21 01:12:35,39,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
39,"Oui, j'accepte de participer",2025-02-05 00:00:00,Diogène,45.0,Homme,Thomassique,Matelgate,Dalegran,Secondaire,4.0,...,2025-02-21 01:14:15,40,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246
40,"Oui, j'accepte de participer",2025-02-05 00:00:00,Mathilde,37.0,Femme,Thomassique,Matelgate,Dalegran,Secondaire,2.0,...,2025-02-21 01:16:55,41,n/a,-1,n/a,n/a,202502201923,n/a,thalie,839246

## univariate qUALITATIVE

In [8]:
class QuantitativeData:
    def __init__(self, data):
        # Convertir "n/a" en NaN (Not a Number) pour les ignorer dans les calculs
        self.data = [np.nan if str(x).lower() in ["n/a", "na", ""] else x for x in data]

    def mean(self):
        """Calcule la moyenne en ignorant les NaN."""
        return np.nanmean(self.data)

    def median(self):
        """Calcule la médiane en ignorant les NaN."""
        return np.nanmedian(self.data)

    def mode(self):
        """Calcule le mode en ignorant les NaN."""
        try:
            return stats.mode([x for x in self.data if not np.isnan(x)]).mode
        except:
            return "Aucun mode trouvé"

    def std_dev(self):
        """Calcule l'écart type en ignorant les NaN."""
        return np.nanstd(self.data)

    def range(self):
        """Calcule l'étendue en ignorant les NaN."""
        cleaned_data = [x for x in self.data if not np.isnan(x)]
        return np.max(cleaned_data) - np.min(cleaned_data)

    def variance(self):
        """Calcule la variance en ignorant les NaN."""
        return np.nanvar(self.data)

In [9]:
age = remove_np_fillna["Q2-Veuillez indiquer votre Age."].to_list()
personne_vivant_meme_toit = remove_np_fillna["Q5-Combien de personnes vivent-ils sous le même toit?"].to_list()
montant_total_credit = remove_np_fillna["Q10-Montant total du dernier crédit contracté"].to_list()
temps_ecoule_app_credit = remove_np_fillna["Q11-Temps écoulé entre la demande et l\'approbation du crédit."].to_list()

In [10]:
age_analysis = QuantitativeData(age)
personne_vivant_meme_toit_analysis = QuantitativeData(personne_vivant_meme_toit)
montant_total_credit_analysis = QuantitativeData(montant_total_credit)
temps_ecoule_app_credit_analysis = QuantitativeData(temps_ecoule_app_credit)

In [11]:
resultats = {
    "age": {
        "Moyenne": [age_analysis.mean()],
        "Médiane": [age_analysis.median()],
        "Mode": [age_analysis.mode()],
        "Écart type": [age_analysis.std_dev()],
        "Étendue": [age_analysis.range()],
        "Variance": [age_analysis.variance()]
    },
    "personne_vivant_meme_toit": {
        "Moyenne": [personne_vivant_meme_toit_analysis.mean()],
        "Médiane": [personne_vivant_meme_toit_analysis.median()],
        "Mode": [personne_vivant_meme_toit_analysis.mode()],
        "Écart type": [personne_vivant_meme_toit_analysis.std_dev()],
        "Étendue": [personne_vivant_meme_toit_analysis.range()],
        "Variance": [personne_vivant_meme_toit_analysis.variance()]
    },
    "montant_total_credit": {
        "Moyenne": [montant_total_credit_analysis.mean()],
        "Médiane": [montant_total_credit_analysis.median()],
        "Mode": [montant_total_credit_analysis.mode()],
        "Écart type": [montant_total_credit_analysis.std_dev()],
        "Étendue": [montant_total_credit_analysis.range()],
        "Variance": [montant_total_credit_analysis.variance()]
    },
    "temps_ecoule_app_credit": {
        "Moyenne": [temps_ecoule_app_credit_analysis.mean()],
        "Médiane": [temps_ecoule_app_credit_analysis.median()],
        "Mode": [temps_ecoule_app_credit_analysis.mode()],
        "Écart type": [temps_ecoule_app_credit_analysis.std_dev()],
        "Étendue": [temps_ecoule_app_credit_analysis.range()],
        "Variance": [temps_ecoule_app_credit_analysis.variance()]
    }
}

In [12]:
age_univariate_results = DataFrame(resultats["age"])
personne_vivant_meme_toit_univariate_results = DataFrame(resultats["personne_vivant_meme_toit"])
montant_total_credit_univariate_results = DataFrame(resultats["montant_total_credit"])
temps_ecoule_app_credit_univariate_results = DataFrame(resultats["temps_ecoule_app_credit"])

In [13]:
# Création du fichier Excel avec plusieurs feuilles
with ExcelWriter("Analyse univariee des variables quantitatives.xlsx", engine='openpyxl') as writer:
    # Écrire chaque DataFrame dans une feuille distincte avec des noms raccourcis
    age_univariate_results.to_excel(writer, sheet_name="age", index=False)
    personne_vivant_meme_toit_univariate_results.to_excel(writer, sheet_name="personnes_meme_toit", index=False)
    montant_total_credit_univariate_results.to_excel(writer, sheet_name="montant_credit", index=False)
    temps_ecoule_app_credit_univariate_results.to_excel(writer, sheet_name="temps_approbation", index=False)

    # Ajouter des bordures aux tableaux
    workbook = writer.book
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )

    # Appliquer les bordures à chaque feuille
    for sheet_name in writer.sheets:
        worksheet = writer.sheets[sheet_name]
        for row in worksheet.iter_rows(min_row=1, max_row=worksheet.max_row, min_col=1, max_col=worksheet.max_column):
            for cell in row:
                cell.border = thin_border

## Turn data quality variable with formula

---

(
    Q2,
    Q5,
    q10,
    q11
)

In [14]:
class SturgesTransformer:
    """
    A class to transform variables using Sturges' formula.
    
    The Sturges formula determines the optimal number of bins:
    k = 1 + 3.322 * log10(n)
    
    where:
    - k is the number of bins
    - n is the sample size
    """
    
    def __init__(self):
        """Initialize the transformer."""
        self.bin_edges = None
        self.bin_midpoints = None
        self.n_bins = None
        self.frequencies = None
    
    def _calculate_bins(self, data):
        """
        Calculate the number of bins and bin edges using Sturges' formula.
        
        Parameters:
        ----------
        data : array-like
            Numeric data to calculate bins for
            
        Returns:
        -------
        tuple
            (n_bins, bin_edges, bin_midpoints, frequencies)
        """
        import numpy as np
        import math
        
        # Calculate number of bins using Sturges' formula
        n = len(data)
        n_bins = math.ceil(1 + 3.322 * math.log10(n))
        
        # Create histogram bins
        hist, bin_edges = np.histogram(data, bins=n_bins)
        
        # Calculate bin midpoints
        bin_midpoints = (bin_edges[1:] + bin_edges[:-1]) / 2
        
        return n_bins, bin_edges, bin_midpoints, hist
    
    def transform(self, series):
        """
        Transform a series using Sturges' method.
        
        Parameters:
        ----------
        series : pandas.Series
            The series to transform
            
        Returns:
        -------
        pandas.Series
            Transformed series with n/a values preserved
        """
        # Create a copy to avoid modifying the original
        result = series.copy()
        
        # Identify 'n/a' values to preserve them
        na_mask = series.astype(str).isin(['n/a', 'na', ''])
        
        # Convert to numeric, forcing non-numeric to NaN (but keep track of original n/a values)
        numeric_values = to_numeric(series, errors='coerce')
        
        # Get valid values for transformation (not NaN)
        valid_mask = ~numeric_values.isna()
        valid_values = numeric_values[valid_mask].values
        
        # Skip transformation if no valid values
        if len(valid_values) == 0:
            return series
        
        # Calculate bins
        self.n_bins, self.bin_edges, self.bin_midpoints, self.frequencies = self._calculate_bins(valid_values)
        
        # Transform valid values to bin midpoints
        transformed_values = np.zeros_like(valid_values, dtype=float)
        
        for i, value in enumerate(valid_values):
            # Find the bin this value belongs to
            bin_index = np.digitize(value, self.bin_edges) - 1
            
            # Handle edge case where value equals the maximum
            if bin_index >= len(self.bin_midpoints):
                bin_index = len(self.bin_midpoints) - 1
            
            # Assign the bin midpoint
            transformed_values[i] = self.bin_midpoints[bin_index]
        
        # Create a new series with transformed values
        result = Series(index=series.index, dtype=object)  # Use object dtype to store both numbers and strings
        
        # Assign transformed values
        result[valid_mask] = transformed_values
        
        # Restore original 'n/a' values
        result[na_mask] = 'n/a'
        
        return result
    
    def get_bin_info(self):
        """
        Get information about the bins.
        
        Returns:
        -------
        dict
            Dictionary with bin information
        """
        if self.bin_edges is None:
            return None
        
        return {
            'n_bins': self.n_bins,
            'bin_edges': self.bin_edges,
            'bin_midpoints': self.bin_midpoints,
            'frequencies': self.frequencies
        }

In [15]:
class DataTransformer:
    """
    Class to handle the transformation of multiple variables in a dataset.
    """
    
    def __init__(self, df):
        """
        Initialize with a dataframe.
        
        Parameters:
        ----------
        df : pandas.DataFrame
            The dataframe to transform
        """
        self.df = df
        self.transformers = {}
        self.results = {}
    
    def transform_variable(self, column_name, output_column_name=None):
        """
        Transform a single variable using Sturges method.
        
        Parameters:
        ----------
        column_name : str
            The name of the column to transform
        output_column_name : str, optional
            The name for the transformed column. If None, will use column_name + "_sturges"
            
        Returns:
        -------
        pandas.Series
            Transformed series
        """
        # Create a new transformer for this column
        transformer = SturgesTransformer()
        
        # Apply transformation
        transformed = transformer.transform(self.df[column_name])
        
        # Store the transformer for later reference
        self.transformers[column_name] = transformer
        
        # Determine output column name
        if output_column_name is None:
            output_column_name = f"{column_name}_sturges"
            
        # Store the result
        self.results[column_name] = {
            'transformed': transformed, 
            'output_name': output_column_name
        }
        
        return transformed
    
    def transform_all(self, columns_map):
        """
        Transform multiple variables with specified output names.
        
        Parameters:
        ----------
        columns_map : dict
            Dictionary mapping original column names to output column names
            
        Returns:
        -------
        pandas.DataFrame
            DataFrame with all columns from original df and added transformed columns
        """
                 
        # Create a copy of the original dataframe
        result_df = self.df.copy()
        
        # Transform each variable and add to the result
        for original_col, output_col in columns_map.items():
            transformed = self.transform_variable(original_col, output_col)
            result_df[output_col] = transformed
        
        return result_df
    
    def get_bin_info(self, column_name):
        """
        Get bin information for a transformed variable.
        
        Parameters:
        ----------
        column_name : str
            The name of the column
            
        Returns:
        -------
        dict or None
            Dictionary with bin information or None if not transformed
        """
        if column_name in self.transformers:
            return self.transformers[column_name].get_bin_info()
        return None
    
    def save_to_excel(self, filename="sturges_transformed_variables.xlsx"):
        """
        Save transformed data and bin information to Excel.
        
        Parameters:
        ----------
        filename : str
            The name of the Excel file to create
        """
                 
        if not self.results:
            print("No transformations to save.")
            return
        
        # Create a DataFrame with original data and transformations
        result_df = self.df.copy()
        
        # Add transformed columns
        for col, info in self.results.items():
            result_df[info['output_name']] = info['transformed']
        
        # Write to Excel with multiple sheets
        with ExcelWriter(filename, engine='openpyxl') as writer:
            # Main sheet with all data
            result_df.to_excel(writer, sheet_name="Complete_Dataset", index=False)
            
            # Create sheets with bin information
            for col in self.results.keys():
                bin_info = self.get_bin_info(col)
                if bin_info:
                    # Create a simplified name for the sheet
                    short_name = col.split('-')[0] if '-' in col else col
                    
                    bin_df = DataFrame({
                        'Bin Start': bin_info['bin_edges'][:-1],
                        'Bin End': bin_info['bin_edges'][1:],
                        'Bin Midpoint': bin_info['bin_midpoints'],
                        'Frequency': bin_info['frequencies']
                    })
                    
                    bin_df.to_excel(writer, sheet_name=f"{short_name}_Bins", index=False)
            
            # Create a summary sheet with information about transformations
            summary_data = []
            for col, info in self.results.items():
                bin_info = self.get_bin_info(col)
                if bin_info:
                    summary_data.append({
                        'Original Column': col,
                        'Transformed Column': info['output_name'],
                        'Number of Bins': bin_info['n_bins']
                    })
            
            if summary_data:
                summary_df = DataFrame(summary_data)
                summary_df.to_excel(writer, sheet_name="Transformation_Summary", index=False)
        
        print(f"Transformations saved to {filename}")

In [16]:
columns_to_transform = {
    "Q2-Veuillez indiquer votre Age.": "Age_cont",
    "Q5-Combien de personnes vivent-ils sous le même toit?": "Personnes_toit_cont",
    "Q10-Montant total du dernier crédit contracté": "Montant_credit_cont",
    "Q11-Temps écoulé entre la demande et l'approbation du crédit.": "Temps_approbation_cont"
}

In [17]:
# Create transformer using remove_np_fillna
transformer = DataTransformer(remove_np_fillna)

# Transform all variables
result_df = transformer.transform_all(columns_to_transform)

# Save to Excel
transformer.save_to_excel("variables_continues_sturges.xlsx")

Transformations saved to variables_continues_sturges.xlsx